/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 144
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 67
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 11
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_agent = 2,
  anon_sym_domain = 3,
  anon_sym_license = 4,
  anon_sym_terms = 5,
  anon_sym_privacy = 6,
  anon_sym_description = 7,
  sym_text_content = 8,
  anon_sym_behavior = 9,
  anon_sym_requires = 10,
  anon_sym_input = 11,
  anon_sym_capabilities = 12,
  anon_sym_output = 13,
  anon_sym_type = 14,
  anon_sym_concept = 15,
  anon_sym_LPAREN = 16,
  anon_sym_RPAREN = 17,
  anon_sym_schema = 18,
  anon_sym_COLON = 19,
  sym_optional_marker = 20,
  anon_sym_LBRACK = 21,
  anon_sym_RBRACK = 22,
  anon_sym_Enum = 23,
  anon_sym_COMMA = 24,
  anon_sym_DOT = 25,
  sym_quoted_string = 26,
  sym_url = 27,
  sym_filename = 28,
  sym_comment = 29,
  sym__newline = 30,
  sym__indent = 31,
  sym__dedent = 32,
  sym_manifest = 33,
  sym_statement = 34,
  sym_agent_decl = 35,
  sym_agent_name = 36,
  sym_agent_meta = 37,
  sym_agent_meta_key = 38,
  sym_description_block = 39,
  sym_behavior_block = 40,
  sym_requires_block = 41,
  sym_input_block = 42,
  sym_capabilities_block = 43,
  sym_output_block = 44,
  sym_type_decl = 45,
  sym_type_property = 46,
  sym_concept_prop = 47,
  sym_schema_prop = 48,
  sym_property_decl = 49,
  sym_type_value = 50,
  sym_type_ref = 51,
  sym_type_list = 52,
  sym_type_reference = 53,
  sym_typed_item = 54,
  sym_cap_item = 55,
  sym_bare_string = 56,
  aux_sym_manifest_repeat1 = 57,
  aux_sym_agent_decl_repeat1 = 58,
  aux_sym_agent_name_repeat1 = 59,
  aux_sym_description_block_repeat1 = 60,
  aux_sym_requires_block_repeat1 = 61,
  aux_sym_input_block_repeat1 = 62,
  aux_sym_capabilities_block_repeat1 = 63,
  aux_sym_type_decl_repeat1 = 64,
  aux_sym_type_value_repeat1 = 65,
  aux_sym_type_list_repeat1 = 66,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_agent] = "agent",
  [anon_sym_domain] = "domain",
  [anon_sym_license] = "license",
  [anon_sym_terms] = "terms",
  [anon_sym_privacy] = "privacy",
  [anon_sym_description] = "description",
  [sym_text_content] = "text_content",
  [anon_sym_behavior] = "behavior",
  [anon_sym_requires] = "requires",
  [anon_sym_input] = "input",
  [anon_sym_capabilities] = "capabilities",
  [anon_sym_output] = "output",
  [anon_sym_type] = "type",
  [anon_sym_concept] = "concept",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_schema] = "schema",
  [anon_sym_COLON] = ":",
  [sym_optional_marker] = "optional_marker",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_Enum] = "Enum",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [sym_quoted_string] = "quoted_string",
  [sym_url] = "url",
  [sym_filename] = "filename",
  [sym_comment] = "comment",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym_manifest] = "manifest",
  [sym_statement] = "statement",
  [sym_agent_decl] = "agent_decl",
  [sym_agent_name] = "agent_name",
  [sym_agent_meta] = "agent_meta",
  [sym_agent_meta_key] = "agent_meta_key",
  [sym_description_block] = "description_block",
  [sym_behavior_block] = "behavior_block",
  [sym_requires_block] = "requires_block",
  [sym_input_block] = "input_block",
  [sym_capabilities_block] = "capabilities_block",
  [sym_output_block] = "output_block",
  [sym_type_decl] = "type_decl",
  [sym_type_property] = "type_property",
  [sym_concept_prop] = "concept_prop",
  [sym_schema_prop] = "schema_prop",
  [sym_property_decl] = "property_decl",
  [sym_type_value] = "type_value",
  [sym_type_ref] = "type_ref",
  [sym_type_list] = "type_list",
  [sym_type_reference] = "type_reference",
  [sym_typed_item] = "typed_item",
  [sym_cap_item] = "cap_item",
  [sym_bare_string] = "bare_string",
  [aux_sym_manifest_repeat1] = "manifest_repeat1",
  [aux_sym_agent_decl_repeat1] = "agent_decl_repeat1",
  [aux_sym_agent_name_repeat1] = "agent_name_repeat1",
  [aux_sym_description_block_repeat1] = "description_block_repeat1",
  [aux_sym_requires_block_repeat1] = "requires_block_repeat1",
  [aux_sym_input_block_repeat1] = "input_block_repeat1",
  [aux_sym_capabilities_block_repeat1] = "capabilities_block_repeat1",
  [aux_sym_type_decl_repeat1] = "type_decl_repeat1",
  [aux_sym_type_value_repeat1] = "type_value_repeat1",
  [aux_sym_type_list_repeat1] = "type_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_agent] = anon_sym_agent,
  [anon_sym_domain] = anon_sym_domain,
  [anon_sym_license] = anon_sym_license,
  [anon_sym_terms] = anon_sym_terms,
  [anon_sym_privacy] = anon_sym_privacy,
  [anon_sym_description] = anon_sym_description,
  [sym_text_content] = sym_text_content,
  [anon_sym_behavior] = anon_sym_behavior,
  [anon_sym_requires] = anon_sym_requires,
  [anon_sym_input] = anon_sym_input,
  [anon_sym_capabilities] = anon_sym_capabilities,
  [anon_sym_output] = anon_sym_output,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_concept] = anon_sym_concept,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_schema] = anon_sym_schema,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_optional_marker] = sym_optional_marker,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_Enum] = anon_sym_Enum,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_quoted_string] = sym_quoted_string,
  [sym_url] = sym_url,
  [sym_filename] = sym_filename,
  [sym_comment] = sym_comment,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym_manifest] = sym_manifest,
  [sym_statement] = sym_statement,
  [sym_agent_decl] = sym_agent_decl,
  [sym_agent_name] = sym_agent_name,
  [sym_agent_meta] = sym_agent_meta,
  [sym_agent_meta_key] = sym_agent_meta_key,
  [sym_description_block] = sym_description_block,
  [sym_behavior_block] = sym_behavior_block,
  [sym_requires_block] = sym_requires_block,
  [sym_input_block] = sym_input_block,
  [sym_capabilities_block] = sym_capabilities_block,
  [sym_output_block] = sym_output_block,
  [sym_type_decl] = sym_type_decl,
  [sym_type_property] = sym_type_property,
  [sym_concept_prop] = sym_concept_prop,
  [sym_schema_prop] = sym_schema_prop,
  [sym_property_decl] = sym_property_decl,
  [sym_type_value] = sym_type_value,
  [sym_type_ref] = sym_type_ref,
  [sym_type_list] = sym_type_list,
  [sym_type_reference] = sym_type_reference,
  [sym_typed_item] = sym_typed_item,
  [sym_cap_item] = sym_cap_item,
  [sym_bare_string] = sym_bare_string,
  [aux_sym_manifest_repeat1] = aux_sym_manifest_repeat1,
  [aux_sym_agent_decl_repeat1] = aux_sym_agent_decl_repeat1,
  [aux_sym_agent_name_repeat1] = aux_sym_agent_name_repeat1,
  [aux_sym_description_block_repeat1] = aux_sym_description_block_repeat1,
  [aux_sym_requires_block_repeat1] = aux_sym_requires_block_repeat1,
  [aux_sym_input_block_repeat1] = aux_sym_input_block_repeat1,
  [aux_sym_capabilities_block_repeat1] = aux_sym_capabilities_block_repeat1,
  [aux_sym_type_decl_repeat1] = aux_sym_type_decl_repeat1,
  [aux_sym_type_value_repeat1] = aux_sym_type_value_repeat1,
  [aux_sym_type_list_repeat1] = aux_sym_type_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_agent] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_domain] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_license] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_terms] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_privacy] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_description] = {
    .visible = true,
    .named = false,
  },
  [sym_text_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_behavior] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_requires] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_input] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_capabilities] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_output] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_concept] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_schema] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_optional_marker] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [sym_filename] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym_manifest] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_agent_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_agent_name] = {
    .visible = true,
    .named = true,
  },
  [sym_agent_meta] = {
    .visible = true,
    .named = true,
  },
  [sym_agent_meta_key] = {
    .visible = true,
    .named = true,
  },
  [sym_description_block] = {
    .visible = true,
    .named = true,
  },
  [sym_behavior_block] = {
    .visible = true,
    .named = true,
  },
  [sym_requires_block] = {
    .visible = true,
    .named = true,
  },
  [sym_input_block] = {
    .visible = true,
    .named = true,
  },
  [sym_capabilities_block] = {
    .visible = true,
    .named = true,
  },
  [sym_output_block] = {
    .visible = true,
    .named = true,
  },
  [sym_type_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_type_property] = {
    .visible = true,
    .named = true,
  },
  [sym_concept_prop] = {
    .visible = true,
    .named = true,
  },
  [sym_schema_prop] = {
    .visible = true,
    .named = true,
  },
  [sym_property_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_type_value] = {
    .visible = true,
    .named = true,
  },
  [sym_type_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_type_list] = {
    .visible = true,
    .named = true,
  },
  [sym_type_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_typed_item] = {
    .visible = true,
    .named = true,
  },
  [sym_cap_item] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_manifest_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_agent_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_agent_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_description_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_requires_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_input_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_capabilities_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_annotation = 1,
  field_description = 2,
  field_file = 3,
  field_key = 4,
  field_label = 5,
  field_name = 6,
  field_optional_marker = 7,
  field_type = 8,
  field_uri = 9,
  field_value = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_annotation] = "annotation",
  [field_description] = "description",
  [field_file] = "file",
  [field_key] = "key",
  [field_label] = "label",
  [field_name] = "name",
  [field_optional_marker] = "optional_marker",
  [field_type] = "type",
  [field_uri] = "uri",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 3},
  [8] = {.index = 11, .length = 3},
  [9] = {.index = 14, .length = 2},
  [10] = {.index = 16, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_file, 1},
  [2] =
    {field_key, 0},
    {field_value, 1},
  [4] =
    {field_annotation, 2},
  [5] =
    {field_uri, 1},
  [6] =
    {field_name, 0},
    {field_type, 2},
  [8] =
    {field_description, 3},
    {field_name, 0},
    {field_type, 2},
  [11] =
    {field_name, 0},
    {field_optional_marker, 1},
    {field_type, 3},
  [14] =
    {field_label, 3},
    {field_uri, 1},
  [16] =
    {field_description, 4},
    {field_name, 0},
    {field_optional_marker, 1},
    {field_type, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 36,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 50,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 49,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 90,
  [113] = 113,
  [114] = 36,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 111,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 111,
  [138] = 138,
  [139] = 50,
  [140] = 130,
  [141] = 125,
  [142] = 130,
  [143] = 134,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 3,
        '(', 18,
        ')', 19,
        ',', 24,
        '.', 25,
        '/', 5,
        ':', 20,
        '?', 21,
        '[', 22,
        ']', 23,
        'h', 39,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == 'h') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(41);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ')') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '[') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '\r') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_optional_marker);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_url);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ')') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_filename);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == 's') ADVANCE(30);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == 'p') ADVANCE(29);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == 't') ADVANCE(32);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == 's') ADVANCE(36);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(35);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(37);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(38);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'E', 1,
        'a', 2,
        'b', 3,
        'c', 4,
        'd', 5,
        'i', 6,
        'l', 7,
        'o', 8,
        'p', 9,
        'r', 10,
        's', 11,
        't', 12,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == 'g') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(16);
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(18);
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(26);
      if (lookahead == 'y') ADVANCE(27);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 15:
      if (lookahead == 'h') ADVANCE(30);
      END_STATE();
    case 16:
      if (lookahead == 'p') ADVANCE(31);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 19:
      if (lookahead == 'm') ADVANCE(34);
      END_STATE();
    case 20:
      if (lookahead == 'p') ADVANCE(35);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(36);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 24:
      if (lookahead == 'q') ADVANCE(39);
      END_STATE();
    case 25:
      if (lookahead == 'h') ADVANCE(40);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(41);
      END_STATE();
    case 27:
      if (lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 28:
      if (lookahead == 'm') ADVANCE(43);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 30:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(46);
      END_STATE();
    case 32:
      if (lookahead == 'c') ADVANCE(47);
      END_STATE();
    case 33:
      if (lookahead == 'c') ADVANCE(48);
      END_STATE();
    case 34:
      if (lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(50);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 37:
      if (lookahead == 'p') ADVANCE(52);
      END_STATE();
    case 38:
      if (lookahead == 'v') ADVANCE(53);
      END_STATE();
    case 39:
      if (lookahead == 'u') ADVANCE(54);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 41:
      if (lookahead == 'm') ADVANCE(56);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_Enum);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 45:
      if (lookahead == 'v') ADVANCE(59);
      END_STATE();
    case 46:
      if (lookahead == 'b') ADVANCE(60);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 48:
      if (lookahead == 'r') ADVANCE(62);
      END_STATE();
    case 49:
      if (lookahead == 'i') ADVANCE(63);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(64);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(65);
      END_STATE();
    case 52:
      if (lookahead == 'u') ADVANCE(66);
      END_STATE();
    case 53:
      if (lookahead == 'a') ADVANCE(67);
      END_STATE();
    case 54:
      if (lookahead == 'i') ADVANCE(68);
      END_STATE();
    case 55:
      if (lookahead == 'm') ADVANCE(69);
      END_STATE();
    case 56:
      if (lookahead == 's') ADVANCE(70);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_agent);
      END_STATE();
    case 59:
      if (lookahead == 'i') ADVANCE(71);
      END_STATE();
    case 60:
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 61:
      if (lookahead == 'p') ADVANCE(73);
      END_STATE();
    case 62:
      if (lookahead == 'i') ADVANCE(74);
      END_STATE();
    case 63:
      if (lookahead == 'n') ADVANCE(75);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_input);
      END_STATE();
    case 65:
      if (lookahead == 's') ADVANCE(76);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(77);
      END_STATE();
    case 67:
      if (lookahead == 'c') ADVANCE(78);
      END_STATE();
    case 68:
      if (lookahead == 'r') ADVANCE(79);
      END_STATE();
    case 69:
      if (lookahead == 'a') ADVANCE(80);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_terms);
      END_STATE();
    case 71:
      if (lookahead == 'o') ADVANCE(81);
      END_STATE();
    case 72:
      if (lookahead == 'l') ADVANCE(82);
      END_STATE();
    case 73:
      if (lookahead == 't') ADVANCE(83);
      END_STATE();
    case 74:
      if (lookahead == 'p') ADVANCE(84);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_domain);
      END_STATE();
    case 76:
      if (lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_output);
      END_STATE();
    case 78:
      if (lookahead == 'y') ADVANCE(86);
      END_STATE();
    case 79:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_schema);
      END_STATE();
    case 81:
      if (lookahead == 'r') ADVANCE(88);
      END_STATE();
    case 82:
      if (lookahead == 'i') ADVANCE(89);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_concept);
      END_STATE();
    case 84:
      if (lookahead == 't') ADVANCE(90);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_license);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_privacy);
      END_STATE();
    case 87:
      if (lookahead == 's') ADVANCE(91);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_behavior);
      END_STATE();
    case 89:
      if (lookahead == 't') ADVANCE(92);
      END_STATE();
    case 90:
      if (lookahead == 'i') ADVANCE(93);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_requires);
      END_STATE();
    case 92:
      if (lookahead == 'i') ADVANCE(94);
      END_STATE();
    case 93:
      if (lookahead == 'o') ADVANCE(95);
      END_STATE();
    case 94:
      if (lookahead == 'e') ADVANCE(96);
      END_STATE();
    case 95:
      if (lookahead == 'n') ADVANCE(97);
      END_STATE();
    case 96:
      if (lookahead == 's') ADVANCE(98);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_description);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_capabilities);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 12, .external_lex_state = 2},
  [2] = {.lex_state = 12, .external_lex_state = 2},
  [3] = {.lex_state = 12, .external_lex_state = 2},
  [4] = {.lex_state = 12, .external_lex_state = 2},
  [5] = {.lex_state = 12, .external_lex_state = 2},
  [6] = {.lex_state = 12, .external_lex_state = 2},
  [7] = {.lex_state = 12, .external_lex_state = 2},
  [8] = {.lex_state = 12, .external_lex_state = 2},
  [9] = {.lex_state = 12, .external_lex_state = 2},
  [10] = {.lex_state = 12, .external_lex_state = 2},
  [11] = {.lex_state = 12, .external_lex_state = 2},
  [12] = {.lex_state = 12, .external_lex_state = 2},
  [13] = {.lex_state = 12, .external_lex_state = 2},
  [14] = {.lex_state = 12, .external_lex_state = 2},
  [15] = {.lex_state = 12, .external_lex_state = 2},
  [16] = {.lex_state = 12, .external_lex_state = 2},
  [17] = {.lex_state = 12, .external_lex_state = 2},
  [18] = {.lex_state = 12, .external_lex_state = 2},
  [19] = {.lex_state = 12, .external_lex_state = 2},
  [20] = {.lex_state = 12, .external_lex_state = 2},
  [21] = {.lex_state = 12, .external_lex_state = 2},
  [22] = {.lex_state = 12, .external_lex_state = 2},
  [23] = {.lex_state = 12, .external_lex_state = 2},
  [24] = {.lex_state = 12, .external_lex_state = 2},
  [25] = {.lex_state = 12},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 12, .external_lex_state = 3},
  [31] = {.lex_state = 12, .external_lex_state = 3},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 12, .external_lex_state = 3},
  [34] = {.lex_state = 12, .external_lex_state = 3},
  [35] = {.lex_state = 12},
  [36] = {.lex_state = 0, .external_lex_state = 4},
  [37] = {.lex_state = 12},
  [38] = {.lex_state = 12},
  [39] = {.lex_state = 12},
  [40] = {.lex_state = 12},
  [41] = {.lex_state = 12, .external_lex_state = 5},
  [42] = {.lex_state = 12, .external_lex_state = 5},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 12},
  [46] = {.lex_state = 0, .external_lex_state = 2},
  [47] = {.lex_state = 12, .external_lex_state = 5},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 0, .external_lex_state = 4},
  [50] = {.lex_state = 0, .external_lex_state = 4},
  [51] = {.lex_state = 0, .external_lex_state = 4},
  [52] = {.lex_state = 0, .external_lex_state = 4},
  [53] = {.lex_state = 0, .external_lex_state = 4},
  [54] = {.lex_state = 12},
  [55] = {.lex_state = 0, .external_lex_state = 4},
  [56] = {.lex_state = 0, .external_lex_state = 2},
  [57] = {.lex_state = 0, .external_lex_state = 2},
  [58] = {.lex_state = 0, .external_lex_state = 4},
  [59] = {.lex_state = 0, .external_lex_state = 4},
  [60] = {.lex_state = 0, .external_lex_state = 4},
  [61] = {.lex_state = 0, .external_lex_state = 4},
  [62] = {.lex_state = 0, .external_lex_state = 4},
  [63] = {.lex_state = 12},
  [64] = {.lex_state = 0, .external_lex_state = 4},
  [65] = {.lex_state = 0, .external_lex_state = 4},
  [66] = {.lex_state = 0, .external_lex_state = 4},
  [67] = {.lex_state = 0, .external_lex_state = 4},
  [68] = {.lex_state = 0, .external_lex_state = 4},
  [69] = {.lex_state = 0, .external_lex_state = 4},
  [70] = {.lex_state = 12},
  [71] = {.lex_state = 0, .external_lex_state = 4},
  [72] = {.lex_state = 0, .external_lex_state = 4},
  [73] = {.lex_state = 0, .external_lex_state = 4},
  [74] = {.lex_state = 0, .external_lex_state = 4},
  [75] = {.lex_state = 0, .external_lex_state = 2},
  [76] = {.lex_state = 0, .external_lex_state = 4},
  [77] = {.lex_state = 0, .external_lex_state = 4},
  [78] = {.lex_state = 0, .external_lex_state = 4},
  [79] = {.lex_state = 0, .external_lex_state = 4},
  [80] = {.lex_state = 0, .external_lex_state = 4},
  [81] = {.lex_state = 0, .external_lex_state = 4},
  [82] = {.lex_state = 0, .external_lex_state = 4},
  [83] = {.lex_state = 0, .external_lex_state = 4},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0, .external_lex_state = 4},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0, .external_lex_state = 4},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0, .external_lex_state = 2},
  [90] = {.lex_state = 0, .external_lex_state = 4},
  [91] = {.lex_state = 0, .external_lex_state = 2},
  [92] = {.lex_state = 0, .external_lex_state = 4},
  [93] = {.lex_state = 0, .external_lex_state = 4},
  [94] = {.lex_state = 0, .external_lex_state = 4},
  [95] = {.lex_state = 12},
  [96] = {.lex_state = 0, .external_lex_state = 4},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 12},
  [99] = {.lex_state = 0, .external_lex_state = 4},
  [100] = {.lex_state = 0, .external_lex_state = 2},
  [101] = {.lex_state = 0, .external_lex_state = 4},
  [102] = {.lex_state = 0, .external_lex_state = 4},
  [103] = {.lex_state = 0, .external_lex_state = 4},
  [104] = {.lex_state = 0, .external_lex_state = 4},
  [105] = {.lex_state = 0, .external_lex_state = 4},
  [106] = {.lex_state = 0, .external_lex_state = 4},
  [107] = {.lex_state = 0, .external_lex_state = 4},
  [108] = {.lex_state = 0, .external_lex_state = 5},
  [109] = {.lex_state = 0, .external_lex_state = 4},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0, .external_lex_state = 4},
  [112] = {.lex_state = 0, .external_lex_state = 2},
  [113] = {.lex_state = 0, .external_lex_state = 4},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0, .external_lex_state = 3},
  [116] = {.lex_state = 0, .external_lex_state = 2},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 12},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0, .external_lex_state = 2},
  [122] = {.lex_state = 1},
  [123] = {.lex_state = 12},
  [124] = {.lex_state = 0, .external_lex_state = 3},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 12},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 7},
  [130] = {.lex_state = 12},
  [131] = {.lex_state = 0, .external_lex_state = 2},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 7},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0, .external_lex_state = 2},
  [136] = {.lex_state = 0, .external_lex_state = 2},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0, .external_lex_state = 2},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 12},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 12},
  [143] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_agent] = ACTIONS(1),
    [anon_sym_domain] = ACTIONS(1),
    [anon_sym_license] = ACTIONS(1),
    [anon_sym_terms] = ACTIONS(1),
    [anon_sym_privacy] = ACTIONS(1),
    [anon_sym_description] = ACTIONS(1),
    [anon_sym_behavior] = ACTIONS(1),
    [anon_sym_requires] = ACTIONS(1),
    [anon_sym_input] = ACTIONS(1),
    [anon_sym_capabilities] = ACTIONS(1),
    [anon_sym_output] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_concept] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_schema] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_optional_marker] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_Enum] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [sym_url] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_manifest] = STATE(126),
    [sym_statement] = STATE(2),
    [sym_agent_decl] = STATE(5),
    [sym_description_block] = STATE(5),
    [sym_behavior_block] = STATE(5),
    [sym_requires_block] = STATE(5),
    [sym_input_block] = STATE(5),
    [sym_capabilities_block] = STATE(5),
    [sym_output_block] = STATE(5),
    [sym_type_decl] = STATE(5),
    [aux_sym_manifest_repeat1] = STATE(2),
    [anon_sym_agent] = ACTIONS(5),
    [anon_sym_description] = ACTIONS(7),
    [anon_sym_behavior] = ACTIONS(9),
    [anon_sym_requires] = ACTIONS(11),
    [anon_sym_input] = ACTIONS(13),
    [anon_sym_capabilities] = ACTIONS(15),
    [anon_sym_output] = ACTIONS(17),
    [anon_sym_type] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_agent,
    ACTIONS(7), 1,
      anon_sym_description,
    ACTIONS(9), 1,
      anon_sym_behavior,
    ACTIONS(11), 1,
      anon_sym_requires,
    ACTIONS(13), 1,
      anon_sym_input,
    ACTIONS(15), 1,
      anon_sym_capabilities,
    ACTIONS(17), 1,
      anon_sym_output,
    ACTIONS(19), 1,
      anon_sym_type,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym__newline,
    STATE(3), 2,
      sym_statement,
      aux_sym_manifest_repeat1,
    STATE(5), 8,
      sym_agent_decl,
      sym_description_block,
      sym_behavior_block,
      sym_requires_block,
      sym_input_block,
      sym_capabilities_block,
      sym_output_block,
      sym_type_decl,
  [48] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      anon_sym_agent,
    ACTIONS(32), 1,
      anon_sym_description,
    ACTIONS(35), 1,
      anon_sym_behavior,
    ACTIONS(38), 1,
      anon_sym_requires,
    ACTIONS(41), 1,
      anon_sym_input,
    ACTIONS(44), 1,
      anon_sym_capabilities,
    ACTIONS(47), 1,
      anon_sym_output,
    ACTIONS(50), 1,
      anon_sym_type,
    ACTIONS(53), 1,
      sym__newline,
    STATE(3), 2,
      sym_statement,
      aux_sym_manifest_repeat1,
    STATE(5), 8,
      sym_agent_decl,
      sym_description_block,
      sym_behavior_block,
      sym_requires_block,
      sym_input_block,
      sym_capabilities_block,
      sym_output_block,
      sym_type_decl,
  [96] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [112] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [128] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [144] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [160] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [176] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [192] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [208] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [224] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [240] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [256] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [272] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [288] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [304] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [320] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [336] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [352] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [368] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [384] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [400] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [416] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 10,
      sym__newline,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [432] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      sym_identifier,
    ACTIONS(100), 1,
      anon_sym_concept,
    ACTIONS(102), 1,
      anon_sym_schema,
    STATE(61), 1,
      sym_type_property,
    STATE(99), 3,
      sym_concept_prop,
      sym_schema_prop,
      sym_property_decl,
  [453] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      sym_identifier,
    ACTIONS(100), 1,
      anon_sym_concept,
    ACTIONS(102), 1,
      anon_sym_schema,
    STATE(101), 1,
      sym_type_property,
    STATE(99), 3,
      sym_concept_prop,
      sym_schema_prop,
      sym_property_decl,
  [474] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(29), 1,
      sym_agent_meta_key,
    STATE(52), 1,
      sym_agent_meta,
    ACTIONS(104), 4,
      anon_sym_domain,
      anon_sym_license,
      anon_sym_terms,
      anon_sym_privacy,
  [490] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(29), 1,
      sym_agent_meta_key,
    STATE(96), 1,
      sym_agent_meta,
    ACTIONS(104), 4,
      anon_sym_domain,
      anon_sym_license,
      anon_sym_terms,
      anon_sym_privacy,
  [506] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      sym_identifier,
    ACTIONS(110), 1,
      sym_url,
    STATE(104), 1,
      sym_bare_string,
    ACTIONS(108), 2,
      sym_quoted_string,
      sym_filename,
  [523] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(114), 1,
      sym__indent,
    STATE(75), 1,
      sym_type_ref,
    STATE(89), 1,
      sym_type_reference,
    STATE(135), 1,
      sym_type_list,
  [542] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(116), 1,
      sym__indent,
    STATE(75), 1,
      sym_type_ref,
    STATE(89), 1,
      sym_type_reference,
    STATE(138), 1,
      sym_type_list,
  [561] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      sym_identifier,
    ACTIONS(120), 1,
      anon_sym_LBRACK,
    ACTIONS(122), 1,
      anon_sym_Enum,
    STATE(78), 1,
      sym_type_value,
    STATE(79), 1,
      sym_type_ref,
  [580] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(124), 1,
      sym__indent,
    STATE(75), 1,
      sym_type_ref,
    STATE(89), 1,
      sym_type_reference,
    STATE(131), 1,
      sym_type_list,
  [599] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(126), 1,
      sym__indent,
    STATE(75), 1,
      sym_type_ref,
    STATE(89), 1,
      sym_type_reference,
    STATE(116), 1,
      sym_type_list,
  [618] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      sym_identifier,
    ACTIONS(120), 1,
      anon_sym_LBRACK,
    ACTIONS(122), 1,
      anon_sym_Enum,
    STATE(79), 1,
      sym_type_ref,
    STATE(82), 1,
      sym_type_value,
  [637] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_DOT,
    ACTIONS(128), 4,
      sym__newline,
      sym__dedent,
      anon_sym_LPAREN,
      sym_quoted_string,
  [650] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(49), 1,
      sym_type_ref,
    STATE(72), 1,
      sym_type_reference,
    STATE(73), 1,
      sym_typed_item,
  [666] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(49), 1,
      sym_type_ref,
    STATE(77), 1,
      sym_type_reference,
    STATE(93), 1,
      sym_cap_item,
  [682] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(49), 1,
      sym_type_ref,
    STATE(72), 1,
      sym_type_reference,
    STATE(85), 1,
      sym_typed_item,
  [698] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(49), 1,
      sym_type_ref,
    STATE(77), 1,
      sym_type_reference,
    STATE(80), 1,
      sym_cap_item,
  [714] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      sym_identifier,
    STATE(42), 1,
      aux_sym_agent_name_repeat1,
    ACTIONS(136), 2,
      sym__newline,
      sym__indent,
  [728] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      sym_identifier,
    STATE(42), 1,
      aux_sym_agent_name_repeat1,
    ACTIONS(141), 2,
      sym__newline,
      sym__indent,
  [742] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identifier,
    ACTIONS(145), 3,
      sym_quoted_string,
      sym_url,
      sym_filename,
  [754] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      sym_identifier,
    STATE(136), 1,
      sym_bare_string,
    ACTIONS(149), 2,
      sym_quoted_string,
      sym_filename,
  [768] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(49), 1,
      sym_type_ref,
    STATE(72), 1,
      sym_type_reference,
    STATE(113), 1,
      sym_typed_item,
  [784] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_DOT,
    ACTIONS(128), 3,
      sym__newline,
      anon_sym_LPAREN,
      anon_sym_COMMA,
  [796] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_identifier,
    STATE(41), 1,
      aux_sym_agent_name_repeat1,
    ACTIONS(155), 2,
      sym__newline,
      sym__indent,
  [810] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      sym_identifier,
    STATE(117), 1,
      sym_bare_string,
    ACTIONS(159), 2,
      sym_quoted_string,
      sym_filename,
  [824] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_LPAREN,
    ACTIONS(163), 3,
      sym__newline,
      sym__dedent,
      sym_quoted_string,
  [836] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 4,
      sym__newline,
      sym__dedent,
      anon_sym_LPAREN,
      sym_quoted_string,
  [846] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 3,
      sym__newline,
      sym__dedent,
      sym_quoted_string,
  [855] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      sym__newline,
    ACTIONS(171), 1,
      sym__dedent,
    STATE(64), 1,
      aux_sym_agent_decl_repeat1,
  [868] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym__newline,
    ACTIONS(175), 1,
      sym__dedent,
    STATE(66), 1,
      aux_sym_description_block_repeat1,
  [881] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(49), 1,
      sym_type_ref,
    STATE(109), 1,
      sym_type_reference,
  [894] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym__newline,
    ACTIONS(179), 1,
      sym__dedent,
    STATE(67), 1,
      aux_sym_requires_block_repeat1,
  [907] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 3,
      sym__newline,
      anon_sym_LPAREN,
      anon_sym_COMMA,
  [916] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    ACTIONS(184), 1,
      sym__newline,
    STATE(57), 1,
      aux_sym_type_list_repeat1,
  [929] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym__newline,
    ACTIONS(188), 1,
      sym__dedent,
    STATE(68), 1,
      aux_sym_input_block_repeat1,
  [942] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      sym__newline,
    ACTIONS(192), 1,
      sym__dedent,
    STATE(69), 1,
      aux_sym_capabilities_block_repeat1,
  [955] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym__newline,
    ACTIONS(194), 1,
      sym__dedent,
    STATE(68), 1,
      aux_sym_input_block_repeat1,
  [968] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      sym__newline,
    ACTIONS(198), 1,
      sym__dedent,
    STATE(74), 1,
      aux_sym_type_decl_repeat1,
  [981] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym__newline,
    ACTIONS(200), 1,
      sym__dedent,
    STATE(53), 1,
      aux_sym_description_block_repeat1,
  [994] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(49), 1,
      sym_type_ref,
    STATE(65), 1,
      sym_type_reference,
  [1007] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      sym__newline,
    ACTIONS(202), 1,
      sym__dedent,
    STATE(76), 1,
      aux_sym_agent_decl_repeat1,
  [1020] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym__newline,
    ACTIONS(204), 1,
      sym__dedent,
    STATE(55), 1,
      aux_sym_requires_block_repeat1,
  [1033] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      sym__newline,
    ACTIONS(209), 1,
      sym__dedent,
    STATE(66), 1,
      aux_sym_description_block_repeat1,
  [1046] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      sym__newline,
    ACTIONS(214), 1,
      sym__dedent,
    STATE(67), 1,
      aux_sym_requires_block_repeat1,
  [1059] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      sym__newline,
    ACTIONS(219), 1,
      sym__dedent,
    STATE(68), 1,
      aux_sym_input_block_repeat1,
  [1072] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      sym__newline,
    ACTIONS(224), 1,
      sym__dedent,
    STATE(69), 1,
      aux_sym_capabilities_block_repeat1,
  [1085] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      sym_identifier,
    STATE(75), 1,
      sym_type_ref,
    STATE(100), 1,
      sym_type_reference,
  [1098] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_LPAREN,
    ACTIONS(228), 2,
      sym__newline,
      sym__dedent,
  [1109] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      sym_quoted_string,
    ACTIONS(232), 2,
      sym__newline,
      sym__dedent,
  [1120] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym__newline,
    ACTIONS(234), 1,
      sym__dedent,
    STATE(58), 1,
      aux_sym_input_block_repeat1,
  [1133] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      sym__newline,
    ACTIONS(236), 1,
      sym__dedent,
    STATE(81), 1,
      aux_sym_type_decl_repeat1,
  [1146] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_LPAREN,
    ACTIONS(163), 2,
      sym__newline,
      anon_sym_COMMA,
  [1157] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      sym__newline,
    ACTIONS(243), 1,
      sym__dedent,
    STATE(76), 1,
      aux_sym_agent_decl_repeat1,
  [1170] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym_quoted_string,
    ACTIONS(247), 2,
      sym__newline,
      sym__dedent,
  [1181] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym_quoted_string,
    ACTIONS(251), 2,
      sym__newline,
      sym__dedent,
  [1192] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 3,
      sym__newline,
      sym__dedent,
      sym_quoted_string,
  [1201] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      sym__newline,
    ACTIONS(255), 1,
      sym__dedent,
    STATE(59), 1,
      aux_sym_capabilities_block_repeat1,
  [1214] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      sym__newline,
    ACTIONS(260), 1,
      sym__dedent,
    STATE(81), 1,
      aux_sym_type_decl_repeat1,
  [1227] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      sym_quoted_string,
    ACTIONS(264), 2,
      sym__newline,
      sym__dedent,
  [1238] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 3,
      sym__newline,
      sym__dedent,
      sym_quoted_string,
  [1247] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
    ACTIONS(270), 1,
      anon_sym_COMMA,
    STATE(86), 1,
      aux_sym_type_value_repeat1,
  [1260] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym__newline,
    ACTIONS(272), 1,
      sym__dedent,
    STATE(60), 1,
      aux_sym_input_block_repeat1,
  [1273] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_COMMA,
    ACTIONS(274), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      aux_sym_type_value_repeat1,
  [1286] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 3,
      sym__newline,
      sym__dedent,
      sym_quoted_string,
  [1295] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_RPAREN,
    ACTIONS(280), 1,
      anon_sym_COMMA,
    STATE(88), 1,
      aux_sym_type_value_repeat1,
  [1308] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_COMMA,
    ACTIONS(285), 1,
      sym__newline,
    STATE(91), 1,
      aux_sym_type_list_repeat1,
  [1321] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 3,
      sym__newline,
      sym__dedent,
      sym_quoted_string,
  [1330] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_COMMA,
    ACTIONS(289), 1,
      sym__newline,
    STATE(57), 1,
      aux_sym_type_list_repeat1,
  [1343] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 2,
      sym__newline,
      sym__dedent,
  [1351] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 2,
      sym__newline,
      sym__dedent,
  [1359] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 2,
      sym__newline,
      sym__dedent,
  [1367] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      sym_identifier,
    STATE(108), 1,
      sym_agent_name,
  [1377] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 2,
      sym__newline,
      sym__dedent,
  [1385] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_COLON,
    ACTIONS(299), 1,
      sym_optional_marker,
  [1395] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      sym_identifier,
    STATE(118), 1,
      sym_type_ref,
  [1405] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 2,
      sym__newline,
      sym__dedent,
  [1413] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 2,
      sym__newline,
      anon_sym_COMMA,
  [1421] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 2,
      sym__newline,
      sym__dedent,
  [1429] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 2,
      sym__newline,
      sym__dedent,
  [1437] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 2,
      sym__newline,
      sym__dedent,
  [1445] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 2,
      sym__newline,
      sym__dedent,
  [1453] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 2,
      sym__newline,
      sym__dedent,
  [1461] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 2,
      sym__newline,
      sym__dedent,
  [1469] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 2,
      sym__newline,
      sym__dedent,
  [1477] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      sym__newline,
    ACTIONS(317), 1,
      sym__indent,
  [1487] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 2,
      sym__newline,
      sym__dedent,
  [1495] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1503] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 2,
      sym__newline,
      sym__dedent,
  [1511] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 2,
      sym__newline,
      anon_sym_COMMA,
  [1519] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 2,
      sym__newline,
      sym__dedent,
  [1527] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      anon_sym_RBRACK,
    ACTIONS(321), 1,
      anon_sym_DOT,
  [1537] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      sym__indent,
  [1544] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      sym__newline,
  [1551] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      anon_sym_RPAREN,
  [1558] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_RBRACK,
  [1565] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      sym_identifier,
  [1572] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      sym_url,
  [1579] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      sym__newline,
  [1586] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      sym_filename,
  [1593] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      sym_identifier,
  [1600] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      sym__indent,
  [1607] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_RPAREN,
  [1614] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      ts_builtin_sym_end,
  [1621] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      sym_identifier,
  [1628] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_LPAREN,
  [1635] = 2,
    ACTIONS(349), 1,
      sym_text_content,
    ACTIONS(351), 1,
      sym_comment,
  [1642] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      sym_identifier,
  [1649] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      sym__newline,
  [1656] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      anon_sym_COLON,
  [1663] = 2,
    ACTIONS(351), 1,
      sym_comment,
    ACTIONS(359), 1,
      sym_text_content,
  [1670] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      sym_quoted_string,
  [1677] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 1,
      sym__newline,
  [1684] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      sym__newline,
  [1691] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_RPAREN,
  [1698] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(367), 1,
      sym__newline,
  [1705] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_RBRACK,
  [1712] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 1,
      sym_identifier,
  [1719] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(371), 1,
      anon_sym_RPAREN,
  [1726] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(373), 1,
      sym_identifier,
  [1733] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(375), 1,
      sym_quoted_string,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 112,
  [SMALL_STATE(6)] = 128,
  [SMALL_STATE(7)] = 144,
  [SMALL_STATE(8)] = 160,
  [SMALL_STATE(9)] = 176,
  [SMALL_STATE(10)] = 192,
  [SMALL_STATE(11)] = 208,
  [SMALL_STATE(12)] = 224,
  [SMALL_STATE(13)] = 240,
  [SMALL_STATE(14)] = 256,
  [SMALL_STATE(15)] = 272,
  [SMALL_STATE(16)] = 288,
  [SMALL_STATE(17)] = 304,
  [SMALL_STATE(18)] = 320,
  [SMALL_STATE(19)] = 336,
  [SMALL_STATE(20)] = 352,
  [SMALL_STATE(21)] = 368,
  [SMALL_STATE(22)] = 384,
  [SMALL_STATE(23)] = 400,
  [SMALL_STATE(24)] = 416,
  [SMALL_STATE(25)] = 432,
  [SMALL_STATE(26)] = 453,
  [SMALL_STATE(27)] = 474,
  [SMALL_STATE(28)] = 490,
  [SMALL_STATE(29)] = 506,
  [SMALL_STATE(30)] = 523,
  [SMALL_STATE(31)] = 542,
  [SMALL_STATE(32)] = 561,
  [SMALL_STATE(33)] = 580,
  [SMALL_STATE(34)] = 599,
  [SMALL_STATE(35)] = 618,
  [SMALL_STATE(36)] = 637,
  [SMALL_STATE(37)] = 650,
  [SMALL_STATE(38)] = 666,
  [SMALL_STATE(39)] = 682,
  [SMALL_STATE(40)] = 698,
  [SMALL_STATE(41)] = 714,
  [SMALL_STATE(42)] = 728,
  [SMALL_STATE(43)] = 742,
  [SMALL_STATE(44)] = 754,
  [SMALL_STATE(45)] = 768,
  [SMALL_STATE(46)] = 784,
  [SMALL_STATE(47)] = 796,
  [SMALL_STATE(48)] = 810,
  [SMALL_STATE(49)] = 824,
  [SMALL_STATE(50)] = 836,
  [SMALL_STATE(51)] = 846,
  [SMALL_STATE(52)] = 855,
  [SMALL_STATE(53)] = 868,
  [SMALL_STATE(54)] = 881,
  [SMALL_STATE(55)] = 894,
  [SMALL_STATE(56)] = 907,
  [SMALL_STATE(57)] = 916,
  [SMALL_STATE(58)] = 929,
  [SMALL_STATE(59)] = 942,
  [SMALL_STATE(60)] = 955,
  [SMALL_STATE(61)] = 968,
  [SMALL_STATE(62)] = 981,
  [SMALL_STATE(63)] = 994,
  [SMALL_STATE(64)] = 1007,
  [SMALL_STATE(65)] = 1020,
  [SMALL_STATE(66)] = 1033,
  [SMALL_STATE(67)] = 1046,
  [SMALL_STATE(68)] = 1059,
  [SMALL_STATE(69)] = 1072,
  [SMALL_STATE(70)] = 1085,
  [SMALL_STATE(71)] = 1098,
  [SMALL_STATE(72)] = 1109,
  [SMALL_STATE(73)] = 1120,
  [SMALL_STATE(74)] = 1133,
  [SMALL_STATE(75)] = 1146,
  [SMALL_STATE(76)] = 1157,
  [SMALL_STATE(77)] = 1170,
  [SMALL_STATE(78)] = 1181,
  [SMALL_STATE(79)] = 1192,
  [SMALL_STATE(80)] = 1201,
  [SMALL_STATE(81)] = 1214,
  [SMALL_STATE(82)] = 1227,
  [SMALL_STATE(83)] = 1238,
  [SMALL_STATE(84)] = 1247,
  [SMALL_STATE(85)] = 1260,
  [SMALL_STATE(86)] = 1273,
  [SMALL_STATE(87)] = 1286,
  [SMALL_STATE(88)] = 1295,
  [SMALL_STATE(89)] = 1308,
  [SMALL_STATE(90)] = 1321,
  [SMALL_STATE(91)] = 1330,
  [SMALL_STATE(92)] = 1343,
  [SMALL_STATE(93)] = 1351,
  [SMALL_STATE(94)] = 1359,
  [SMALL_STATE(95)] = 1367,
  [SMALL_STATE(96)] = 1377,
  [SMALL_STATE(97)] = 1385,
  [SMALL_STATE(98)] = 1395,
  [SMALL_STATE(99)] = 1405,
  [SMALL_STATE(100)] = 1413,
  [SMALL_STATE(101)] = 1421,
  [SMALL_STATE(102)] = 1429,
  [SMALL_STATE(103)] = 1437,
  [SMALL_STATE(104)] = 1445,
  [SMALL_STATE(105)] = 1453,
  [SMALL_STATE(106)] = 1461,
  [SMALL_STATE(107)] = 1469,
  [SMALL_STATE(108)] = 1477,
  [SMALL_STATE(109)] = 1487,
  [SMALL_STATE(110)] = 1495,
  [SMALL_STATE(111)] = 1503,
  [SMALL_STATE(112)] = 1511,
  [SMALL_STATE(113)] = 1519,
  [SMALL_STATE(114)] = 1527,
  [SMALL_STATE(115)] = 1537,
  [SMALL_STATE(116)] = 1544,
  [SMALL_STATE(117)] = 1551,
  [SMALL_STATE(118)] = 1558,
  [SMALL_STATE(119)] = 1565,
  [SMALL_STATE(120)] = 1572,
  [SMALL_STATE(121)] = 1579,
  [SMALL_STATE(122)] = 1586,
  [SMALL_STATE(123)] = 1593,
  [SMALL_STATE(124)] = 1600,
  [SMALL_STATE(125)] = 1607,
  [SMALL_STATE(126)] = 1614,
  [SMALL_STATE(127)] = 1621,
  [SMALL_STATE(128)] = 1628,
  [SMALL_STATE(129)] = 1635,
  [SMALL_STATE(130)] = 1642,
  [SMALL_STATE(131)] = 1649,
  [SMALL_STATE(132)] = 1656,
  [SMALL_STATE(133)] = 1663,
  [SMALL_STATE(134)] = 1670,
  [SMALL_STATE(135)] = 1677,
  [SMALL_STATE(136)] = 1684,
  [SMALL_STATE(137)] = 1691,
  [SMALL_STATE(138)] = 1698,
  [SMALL_STATE(139)] = 1705,
  [SMALL_STATE(140)] = 1712,
  [SMALL_STATE(141)] = 1719,
  [SMALL_STATE(142)] = 1726,
  [SMALL_STATE(143)] = 1733,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_manifest, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(115),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(123),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 5, 0, 1),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_decl, 3, 0, 1),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_block, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_behavior_block, 3, 0, 2),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requires_block, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capabilities_block, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_block, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description_block, 4, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requires_block, 4, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_block, 4, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capabilities_block, 4, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_block, 4, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requires_block, 5, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_decl, 5, 0, 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description_block, 5, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_block, 5, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_block, 5, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capabilities_block, 5, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_decl, 6, 0, 1),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 6, 0, 1),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_ref, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_name, 2, 0, 0),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_agent_name_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_agent_name_repeat1, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_agent_meta_key, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_meta_key, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_name, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(137),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_reference, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_ref, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_value, 4, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_list_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_list_repeat1, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_description_block_repeat1, 2, 0, 0), SHIFT_REPEAT(133),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_description_block_repeat1, 2, 0, 0),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_requires_block_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_requires_block_repeat1, 2, 0, 0),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_input_block_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_input_block_repeat1, 2, 0, 0),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_capabilities_block_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_capabilities_block_repeat1, 2, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_concept_prop, 2, 0, 5),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typed_item, 1, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [240] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_agent_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_agent_decl_repeat1, 2, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cap_item, 1, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_decl, 3, 0, 6),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_value, 1, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [257] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_decl_repeat1, 2, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_decl, 4, 0, 8),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_value, 3, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_value, 5, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_value_repeat1, 2, 0, 0),
  [280] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_value_repeat1, 2, 0, 0), SHIFT_REPEAT(127),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_list, 1, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_reference, 4, 0, 4),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_list, 2, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cap_item, 2, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema_prop, 2, 0, 2),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_property, 1, 0, 0),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typed_item, 2, 0, 0),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_decl, 4, 0, 7),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_meta, 2, 0, 3),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_concept_prop, 5, 0, 9),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_decl, 5, 0, 10),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bare_string, 1, 0, 0),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [343] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [349] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [351] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [359] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
  },
  [3] = {
    [ts_external_token__indent] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
    [ts_external_token__dedent] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_agent_external_scanner_create(void);
void tree_sitter_agent_external_scanner_destroy(void *);
bool tree_sitter_agent_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_agent_external_scanner_serialize(void *, char *);
void tree_sitter_agent_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_agent(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_agent_external_scanner_create,
      tree_sitter_agent_external_scanner_destroy,
      tree_sitter_agent_external_scanner_scan,
      tree_sitter_agent_external_scanner_serialize,
      tree_sitter_agent_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "agent",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
