/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 141
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 66
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 11
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_agent = 2,
  anon_sym_domain = 3,
  anon_sym_license = 4,
  anon_sym_terms = 5,
  anon_sym_privacy = 6,
  anon_sym_description = 7,
  sym_text_content = 8,
  anon_sym_behavior = 9,
  anon_sym_requires = 10,
  anon_sym_input = 11,
  anon_sym_capabilities = 12,
  anon_sym_output = 13,
  anon_sym_type = 14,
  anon_sym_concept = 15,
  anon_sym_LPAREN = 16,
  anon_sym_RPAREN = 17,
  anon_sym_schema = 18,
  anon_sym_COLON = 19,
  anon_sym_QMARK = 20,
  anon_sym_LBRACK = 21,
  anon_sym_RBRACK = 22,
  anon_sym_Enum = 23,
  anon_sym_COMMA = 24,
  anon_sym_DOT = 25,
  sym_quoted_string = 26,
  sym_url = 27,
  sym_filename = 28,
  sym_comment = 29,
  sym__newline = 30,
  sym__indent = 31,
  sym__dedent = 32,
  sym_manifest = 33,
  sym_statement = 34,
  sym_agent_decl = 35,
  sym_agent_name = 36,
  sym_agent_meta = 37,
  sym_description_block = 38,
  sym_behavior_block = 39,
  sym_requires_block = 40,
  sym_input_block = 41,
  sym_capabilities_block = 42,
  sym_output_block = 43,
  sym_type_decl = 44,
  sym_type_property = 45,
  sym_concept_prop = 46,
  sym_schema_prop = 47,
  sym_property_decl = 48,
  sym_type_value = 49,
  sym_type_ref = 50,
  sym_type_list = 51,
  sym_type_reference = 52,
  sym_typed_item = 53,
  sym_cap_item = 54,
  sym_bare_string = 55,
  aux_sym_manifest_repeat1 = 56,
  aux_sym_agent_decl_repeat1 = 57,
  aux_sym_agent_name_repeat1 = 58,
  aux_sym_description_block_repeat1 = 59,
  aux_sym_requires_block_repeat1 = 60,
  aux_sym_input_block_repeat1 = 61,
  aux_sym_capabilities_block_repeat1 = 62,
  aux_sym_type_decl_repeat1 = 63,
  aux_sym_type_value_repeat1 = 64,
  aux_sym_type_list_repeat1 = 65,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_agent] = "agent",
  [anon_sym_domain] = "domain",
  [anon_sym_license] = "license",
  [anon_sym_terms] = "terms",
  [anon_sym_privacy] = "privacy",
  [anon_sym_description] = "description",
  [sym_text_content] = "text_content",
  [anon_sym_behavior] = "behavior",
  [anon_sym_requires] = "requires",
  [anon_sym_input] = "input",
  [anon_sym_capabilities] = "capabilities",
  [anon_sym_output] = "output",
  [anon_sym_type] = "type",
  [anon_sym_concept] = "concept",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_schema] = "schema",
  [anon_sym_COLON] = ":",
  [anon_sym_QMARK] = "\?",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_Enum] = "Enum",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [sym_quoted_string] = "quoted_string",
  [sym_url] = "url",
  [sym_filename] = "filename",
  [sym_comment] = "comment",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym_manifest] = "manifest",
  [sym_statement] = "statement",
  [sym_agent_decl] = "agent_decl",
  [sym_agent_name] = "agent_name",
  [sym_agent_meta] = "agent_meta",
  [sym_description_block] = "description_block",
  [sym_behavior_block] = "behavior_block",
  [sym_requires_block] = "requires_block",
  [sym_input_block] = "input_block",
  [sym_capabilities_block] = "capabilities_block",
  [sym_output_block] = "output_block",
  [sym_type_decl] = "type_decl",
  [sym_type_property] = "type_property",
  [sym_concept_prop] = "concept_prop",
  [sym_schema_prop] = "schema_prop",
  [sym_property_decl] = "property_decl",
  [sym_type_value] = "type_value",
  [sym_type_ref] = "type_ref",
  [sym_type_list] = "type_list",
  [sym_type_reference] = "type_reference",
  [sym_typed_item] = "typed_item",
  [sym_cap_item] = "cap_item",
  [sym_bare_string] = "bare_string",
  [aux_sym_manifest_repeat1] = "manifest_repeat1",
  [aux_sym_agent_decl_repeat1] = "agent_decl_repeat1",
  [aux_sym_agent_name_repeat1] = "agent_name_repeat1",
  [aux_sym_description_block_repeat1] = "description_block_repeat1",
  [aux_sym_requires_block_repeat1] = "requires_block_repeat1",
  [aux_sym_input_block_repeat1] = "input_block_repeat1",
  [aux_sym_capabilities_block_repeat1] = "capabilities_block_repeat1",
  [aux_sym_type_decl_repeat1] = "type_decl_repeat1",
  [aux_sym_type_value_repeat1] = "type_value_repeat1",
  [aux_sym_type_list_repeat1] = "type_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_agent] = anon_sym_agent,
  [anon_sym_domain] = anon_sym_domain,
  [anon_sym_license] = anon_sym_license,
  [anon_sym_terms] = anon_sym_terms,
  [anon_sym_privacy] = anon_sym_privacy,
  [anon_sym_description] = anon_sym_description,
  [sym_text_content] = sym_text_content,
  [anon_sym_behavior] = anon_sym_behavior,
  [anon_sym_requires] = anon_sym_requires,
  [anon_sym_input] = anon_sym_input,
  [anon_sym_capabilities] = anon_sym_capabilities,
  [anon_sym_output] = anon_sym_output,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_concept] = anon_sym_concept,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_schema] = anon_sym_schema,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_Enum] = anon_sym_Enum,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_quoted_string] = sym_quoted_string,
  [sym_url] = sym_url,
  [sym_filename] = sym_filename,
  [sym_comment] = sym_comment,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym_manifest] = sym_manifest,
  [sym_statement] = sym_statement,
  [sym_agent_decl] = sym_agent_decl,
  [sym_agent_name] = sym_agent_name,
  [sym_agent_meta] = sym_agent_meta,
  [sym_description_block] = sym_description_block,
  [sym_behavior_block] = sym_behavior_block,
  [sym_requires_block] = sym_requires_block,
  [sym_input_block] = sym_input_block,
  [sym_capabilities_block] = sym_capabilities_block,
  [sym_output_block] = sym_output_block,
  [sym_type_decl] = sym_type_decl,
  [sym_type_property] = sym_type_property,
  [sym_concept_prop] = sym_concept_prop,
  [sym_schema_prop] = sym_schema_prop,
  [sym_property_decl] = sym_property_decl,
  [sym_type_value] = sym_type_value,
  [sym_type_ref] = sym_type_ref,
  [sym_type_list] = sym_type_list,
  [sym_type_reference] = sym_type_reference,
  [sym_typed_item] = sym_typed_item,
  [sym_cap_item] = sym_cap_item,
  [sym_bare_string] = sym_bare_string,
  [aux_sym_manifest_repeat1] = aux_sym_manifest_repeat1,
  [aux_sym_agent_decl_repeat1] = aux_sym_agent_decl_repeat1,
  [aux_sym_agent_name_repeat1] = aux_sym_agent_name_repeat1,
  [aux_sym_description_block_repeat1] = aux_sym_description_block_repeat1,
  [aux_sym_requires_block_repeat1] = aux_sym_requires_block_repeat1,
  [aux_sym_input_block_repeat1] = aux_sym_input_block_repeat1,
  [aux_sym_capabilities_block_repeat1] = aux_sym_capabilities_block_repeat1,
  [aux_sym_type_decl_repeat1] = aux_sym_type_decl_repeat1,
  [aux_sym_type_value_repeat1] = aux_sym_type_value_repeat1,
  [aux_sym_type_list_repeat1] = aux_sym_type_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_agent] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_domain] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_license] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_terms] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_privacy] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_description] = {
    .visible = true,
    .named = false,
  },
  [sym_text_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_behavior] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_requires] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_input] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_capabilities] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_output] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_concept] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_schema] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [sym_filename] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym_manifest] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_agent_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_agent_name] = {
    .visible = true,
    .named = true,
  },
  [sym_agent_meta] = {
    .visible = true,
    .named = true,
  },
  [sym_description_block] = {
    .visible = true,
    .named = true,
  },
  [sym_behavior_block] = {
    .visible = true,
    .named = true,
  },
  [sym_requires_block] = {
    .visible = true,
    .named = true,
  },
  [sym_input_block] = {
    .visible = true,
    .named = true,
  },
  [sym_capabilities_block] = {
    .visible = true,
    .named = true,
  },
  [sym_output_block] = {
    .visible = true,
    .named = true,
  },
  [sym_type_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_type_property] = {
    .visible = true,
    .named = true,
  },
  [sym_concept_prop] = {
    .visible = true,
    .named = true,
  },
  [sym_schema_prop] = {
    .visible = true,
    .named = true,
  },
  [sym_property_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_type_value] = {
    .visible = true,
    .named = true,
  },
  [sym_type_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_type_list] = {
    .visible = true,
    .named = true,
  },
  [sym_type_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_typed_item] = {
    .visible = true,
    .named = true,
  },
  [sym_cap_item] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_manifest_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_agent_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_agent_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_description_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_requires_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_input_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_capabilities_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_annotation = 1,
  field_description = 2,
  field_file = 3,
  field_key = 4,
  field_label = 5,
  field_name = 6,
  field_optional_marker = 7,
  field_type = 8,
  field_uri = 9,
  field_value = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_annotation] = "annotation",
  [field_description] = "description",
  [field_file] = "file",
  [field_key] = "key",
  [field_label] = "label",
  [field_name] = "name",
  [field_optional_marker] = "optional_marker",
  [field_type] = "type",
  [field_uri] = "uri",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 3},
  [8] = {.index = 11, .length = 3},
  [9] = {.index = 14, .length = 2},
  [10] = {.index = 16, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_file, 1},
  [2] =
    {field_key, 0},
    {field_value, 1},
  [4] =
    {field_annotation, 2},
  [5] =
    {field_uri, 1},
  [6] =
    {field_name, 0},
    {field_type, 2},
  [8] =
    {field_name, 0},
    {field_optional_marker, 3},
    {field_type, 2},
  [11] =
    {field_description, 3},
    {field_name, 0},
    {field_type, 2},
  [14] =
    {field_label, 3},
    {field_uri, 1},
  [16] =
    {field_description, 4},
    {field_name, 0},
    {field_optional_marker, 3},
    {field_type, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 27,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 35,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 51,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 54,
  [111] = 27,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 108,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 108,
  [135] = 135,
  [136] = 35,
  [137] = 115,
  [138] = 120,
  [139] = 115,
  [140] = 123,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 3,
        '(', 17,
        ')', 18,
        ',', 23,
        '.', 24,
        '/', 5,
        ':', 19,
        '?', 20,
        '[', 21,
        ']', 22,
        'h', 38,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == 'h') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(41);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ')') ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '[') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_url);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ')') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_filename);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == 's') ADVANCE(29);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == 'p') ADVANCE(28);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == 't') ADVANCE(30);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == 's') ADVANCE(35);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(34);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(36);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(37);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\r') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'E', 1,
        'a', 2,
        'b', 3,
        'c', 4,
        'd', 5,
        'i', 6,
        'l', 7,
        'o', 8,
        'p', 9,
        'r', 10,
        's', 11,
        't', 12,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == 'g') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(16);
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(18);
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(26);
      if (lookahead == 'y') ADVANCE(27);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 15:
      if (lookahead == 'h') ADVANCE(30);
      END_STATE();
    case 16:
      if (lookahead == 'p') ADVANCE(31);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 19:
      if (lookahead == 'm') ADVANCE(34);
      END_STATE();
    case 20:
      if (lookahead == 'p') ADVANCE(35);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(36);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 24:
      if (lookahead == 'q') ADVANCE(39);
      END_STATE();
    case 25:
      if (lookahead == 'h') ADVANCE(40);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(41);
      END_STATE();
    case 27:
      if (lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 28:
      if (lookahead == 'm') ADVANCE(43);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 30:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 31:
      if (lookahead == 'a') ADVANCE(46);
      END_STATE();
    case 32:
      if (lookahead == 'c') ADVANCE(47);
      END_STATE();
    case 33:
      if (lookahead == 'c') ADVANCE(48);
      END_STATE();
    case 34:
      if (lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(50);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 37:
      if (lookahead == 'p') ADVANCE(52);
      END_STATE();
    case 38:
      if (lookahead == 'v') ADVANCE(53);
      END_STATE();
    case 39:
      if (lookahead == 'u') ADVANCE(54);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 41:
      if (lookahead == 'm') ADVANCE(56);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_Enum);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 45:
      if (lookahead == 'v') ADVANCE(59);
      END_STATE();
    case 46:
      if (lookahead == 'b') ADVANCE(60);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 48:
      if (lookahead == 'r') ADVANCE(62);
      END_STATE();
    case 49:
      if (lookahead == 'i') ADVANCE(63);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(64);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(65);
      END_STATE();
    case 52:
      if (lookahead == 'u') ADVANCE(66);
      END_STATE();
    case 53:
      if (lookahead == 'a') ADVANCE(67);
      END_STATE();
    case 54:
      if (lookahead == 'i') ADVANCE(68);
      END_STATE();
    case 55:
      if (lookahead == 'm') ADVANCE(69);
      END_STATE();
    case 56:
      if (lookahead == 's') ADVANCE(70);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_agent);
      END_STATE();
    case 59:
      if (lookahead == 'i') ADVANCE(71);
      END_STATE();
    case 60:
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 61:
      if (lookahead == 'p') ADVANCE(73);
      END_STATE();
    case 62:
      if (lookahead == 'i') ADVANCE(74);
      END_STATE();
    case 63:
      if (lookahead == 'n') ADVANCE(75);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_input);
      END_STATE();
    case 65:
      if (lookahead == 's') ADVANCE(76);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(77);
      END_STATE();
    case 67:
      if (lookahead == 'c') ADVANCE(78);
      END_STATE();
    case 68:
      if (lookahead == 'r') ADVANCE(79);
      END_STATE();
    case 69:
      if (lookahead == 'a') ADVANCE(80);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_terms);
      END_STATE();
    case 71:
      if (lookahead == 'o') ADVANCE(81);
      END_STATE();
    case 72:
      if (lookahead == 'l') ADVANCE(82);
      END_STATE();
    case 73:
      if (lookahead == 't') ADVANCE(83);
      END_STATE();
    case 74:
      if (lookahead == 'p') ADVANCE(84);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_domain);
      END_STATE();
    case 76:
      if (lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_output);
      END_STATE();
    case 78:
      if (lookahead == 'y') ADVANCE(86);
      END_STATE();
    case 79:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_schema);
      END_STATE();
    case 81:
      if (lookahead == 'r') ADVANCE(88);
      END_STATE();
    case 82:
      if (lookahead == 'i') ADVANCE(89);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_concept);
      END_STATE();
    case 84:
      if (lookahead == 't') ADVANCE(90);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_license);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_privacy);
      END_STATE();
    case 87:
      if (lookahead == 's') ADVANCE(91);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_behavior);
      END_STATE();
    case 89:
      if (lookahead == 't') ADVANCE(92);
      END_STATE();
    case 90:
      if (lookahead == 'i') ADVANCE(93);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_requires);
      END_STATE();
    case 92:
      if (lookahead == 'i') ADVANCE(94);
      END_STATE();
    case 93:
      if (lookahead == 'o') ADVANCE(95);
      END_STATE();
    case 94:
      if (lookahead == 'e') ADVANCE(96);
      END_STATE();
    case 95:
      if (lookahead == 'n') ADVANCE(97);
      END_STATE();
    case 96:
      if (lookahead == 's') ADVANCE(98);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_description);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_capabilities);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 12},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 12},
  [18] = {.lex_state = 12},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 12},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 12},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 12, .external_lex_state = 3},
  [29] = {.lex_state = 12, .external_lex_state = 3},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 12},
  [34] = {.lex_state = 12, .external_lex_state = 3},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {.lex_state = 12, .external_lex_state = 3},
  [37] = {.lex_state = 12},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 0, .external_lex_state = 4},
  [40] = {.lex_state = 12},
  [41] = {.lex_state = 12, .external_lex_state = 5},
  [42] = {.lex_state = 12},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 0, .external_lex_state = 2},
  [45] = {.lex_state = 0, .external_lex_state = 2},
  [46] = {.lex_state = 12},
  [47] = {.lex_state = 0, .external_lex_state = 2},
  [48] = {.lex_state = 0, .external_lex_state = 2},
  [49] = {.lex_state = 0, .external_lex_state = 2},
  [50] = {.lex_state = 12, .external_lex_state = 5},
  [51] = {.lex_state = 0, .external_lex_state = 2},
  [52] = {.lex_state = 12},
  [53] = {.lex_state = 12, .external_lex_state = 5},
  [54] = {.lex_state = 0, .external_lex_state = 2},
  [55] = {.lex_state = 0, .external_lex_state = 2},
  [56] = {.lex_state = 12},
  [57] = {.lex_state = 0, .external_lex_state = 2},
  [58] = {.lex_state = 0, .external_lex_state = 4},
  [59] = {.lex_state = 0, .external_lex_state = 4},
  [60] = {.lex_state = 0, .external_lex_state = 2},
  [61] = {.lex_state = 0, .external_lex_state = 2},
  [62] = {.lex_state = 0, .external_lex_state = 2},
  [63] = {.lex_state = 0, .external_lex_state = 2},
  [64] = {.lex_state = 0, .external_lex_state = 2},
  [65] = {.lex_state = 0, .external_lex_state = 2},
  [66] = {.lex_state = 12},
  [67] = {.lex_state = 0, .external_lex_state = 2},
  [68] = {.lex_state = 0, .external_lex_state = 2},
  [69] = {.lex_state = 0, .external_lex_state = 2},
  [70] = {.lex_state = 0, .external_lex_state = 2},
  [71] = {.lex_state = 0, .external_lex_state = 2},
  [72] = {.lex_state = 0, .external_lex_state = 2},
  [73] = {.lex_state = 0, .external_lex_state = 4},
  [74] = {.lex_state = 0, .external_lex_state = 2},
  [75] = {.lex_state = 0, .external_lex_state = 2},
  [76] = {.lex_state = 0, .external_lex_state = 2},
  [77] = {.lex_state = 0, .external_lex_state = 2},
  [78] = {.lex_state = 0, .external_lex_state = 4},
  [79] = {.lex_state = 0, .external_lex_state = 2},
  [80] = {.lex_state = 0, .external_lex_state = 2},
  [81] = {.lex_state = 0, .external_lex_state = 2},
  [82] = {.lex_state = 0, .external_lex_state = 2},
  [83] = {.lex_state = 0, .external_lex_state = 2},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0, .external_lex_state = 4},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0, .external_lex_state = 2},
  [89] = {.lex_state = 12},
  [90] = {.lex_state = 0, .external_lex_state = 2},
  [91] = {.lex_state = 0, .external_lex_state = 4},
  [92] = {.lex_state = 0, .external_lex_state = 2},
  [93] = {.lex_state = 0, .external_lex_state = 2},
  [94] = {.lex_state = 0, .external_lex_state = 2},
  [95] = {.lex_state = 0, .external_lex_state = 2},
  [96] = {.lex_state = 0, .external_lex_state = 2},
  [97] = {.lex_state = 0, .external_lex_state = 2},
  [98] = {.lex_state = 12},
  [99] = {.lex_state = 0, .external_lex_state = 2},
  [100] = {.lex_state = 0, .external_lex_state = 2},
  [101] = {.lex_state = 0, .external_lex_state = 2},
  [102] = {.lex_state = 0, .external_lex_state = 2},
  [103] = {.lex_state = 0, .external_lex_state = 2},
  [104] = {.lex_state = 0, .external_lex_state = 2},
  [105] = {.lex_state = 0, .external_lex_state = 2},
  [106] = {.lex_state = 0, .external_lex_state = 5},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0, .external_lex_state = 2},
  [109] = {.lex_state = 12},
  [110] = {.lex_state = 0, .external_lex_state = 4},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0, .external_lex_state = 3},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 12},
  [116] = {.lex_state = 12},
  [117] = {.lex_state = 1},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0, .external_lex_state = 4},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 12},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 12},
  [125] = {.lex_state = 0, .external_lex_state = 4},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0, .external_lex_state = 3},
  [128] = {.lex_state = 7},
  [129] = {.lex_state = 0, .external_lex_state = 4},
  [130] = {.lex_state = 0, .external_lex_state = 4},
  [131] = {.lex_state = 0, .external_lex_state = 4},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 7},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0, .external_lex_state = 4},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 12},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 12},
  [140] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_agent] = ACTIONS(1),
    [anon_sym_domain] = ACTIONS(1),
    [anon_sym_license] = ACTIONS(1),
    [anon_sym_terms] = ACTIONS(1),
    [anon_sym_privacy] = ACTIONS(1),
    [anon_sym_description] = ACTIONS(1),
    [anon_sym_behavior] = ACTIONS(1),
    [anon_sym_requires] = ACTIONS(1),
    [anon_sym_input] = ACTIONS(1),
    [anon_sym_capabilities] = ACTIONS(1),
    [anon_sym_output] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_concept] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_schema] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_Enum] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [sym_url] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_manifest] = STATE(121),
    [sym_statement] = STATE(2),
    [sym_agent_decl] = STATE(5),
    [sym_description_block] = STATE(5),
    [sym_behavior_block] = STATE(5),
    [sym_requires_block] = STATE(5),
    [sym_input_block] = STATE(5),
    [sym_capabilities_block] = STATE(5),
    [sym_output_block] = STATE(5),
    [sym_type_decl] = STATE(5),
    [aux_sym_manifest_repeat1] = STATE(2),
    [anon_sym_agent] = ACTIONS(5),
    [anon_sym_description] = ACTIONS(7),
    [anon_sym_behavior] = ACTIONS(9),
    [anon_sym_requires] = ACTIONS(11),
    [anon_sym_input] = ACTIONS(13),
    [anon_sym_capabilities] = ACTIONS(15),
    [anon_sym_output] = ACTIONS(17),
    [anon_sym_type] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_agent,
    ACTIONS(7), 1,
      anon_sym_description,
    ACTIONS(9), 1,
      anon_sym_behavior,
    ACTIONS(11), 1,
      anon_sym_requires,
    ACTIONS(13), 1,
      anon_sym_input,
    ACTIONS(15), 1,
      anon_sym_capabilities,
    ACTIONS(17), 1,
      anon_sym_output,
    ACTIONS(19), 1,
      anon_sym_type,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(3), 2,
      sym_statement,
      aux_sym_manifest_repeat1,
    STATE(5), 8,
      sym_agent_decl,
      sym_description_block,
      sym_behavior_block,
      sym_requires_block,
      sym_input_block,
      sym_capabilities_block,
      sym_output_block,
      sym_type_decl,
  [45] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_agent,
    ACTIONS(28), 1,
      anon_sym_description,
    ACTIONS(31), 1,
      anon_sym_behavior,
    ACTIONS(34), 1,
      anon_sym_requires,
    ACTIONS(37), 1,
      anon_sym_input,
    ACTIONS(40), 1,
      anon_sym_capabilities,
    ACTIONS(43), 1,
      anon_sym_output,
    ACTIONS(46), 1,
      anon_sym_type,
    STATE(3), 2,
      sym_statement,
      aux_sym_manifest_repeat1,
    STATE(5), 8,
      sym_agent_decl,
      sym_description_block,
      sym_behavior_block,
      sym_requires_block,
      sym_input_block,
      sym_capabilities_block,
      sym_output_block,
      sym_type_decl,
  [90] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [105] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [120] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [135] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [150] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [165] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [180] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [195] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [210] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [225] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [240] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [255] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [270] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [285] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [300] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [315] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [330] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [345] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [360] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [375] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [390] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 9,
      ts_builtin_sym_end,
      anon_sym_agent,
      anon_sym_description,
      anon_sym_behavior,
      anon_sym_requires,
      anon_sym_input,
      anon_sym_capabilities,
      anon_sym_output,
      anon_sym_type,
  [405] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_concept,
    ACTIONS(95), 1,
      anon_sym_schema,
    STATE(63), 1,
      sym_type_property,
    STATE(96), 3,
      sym_concept_prop,
      sym_schema_prop,
      sym_property_decl,
  [426] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_concept,
    ACTIONS(95), 1,
      anon_sym_schema,
    STATE(99), 1,
      sym_type_property,
    STATE(96), 3,
      sym_concept_prop,
      sym_schema_prop,
      sym_property_decl,
  [447] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      anon_sym_DOT,
    ACTIONS(97), 5,
      sym__newline,
      sym__dedent,
      anon_sym_LPAREN,
      anon_sym_QMARK,
      sym_quoted_string,
  [461] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym_identifier,
    ACTIONS(103), 1,
      sym__indent,
    STATE(78), 1,
      sym_type_ref,
    STATE(85), 1,
      sym_type_reference,
    STATE(130), 1,
      sym_type_list,
  [480] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym_identifier,
    ACTIONS(105), 1,
      sym__indent,
    STATE(78), 1,
      sym_type_ref,
    STATE(85), 1,
      sym_type_reference,
    STATE(135), 1,
      sym_type_list,
  [499] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(88), 1,
      sym_agent_meta,
    ACTIONS(107), 4,
      anon_sym_domain,
      anon_sym_license,
      anon_sym_terms,
      anon_sym_privacy,
  [512] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_identifier,
    ACTIONS(113), 1,
      sym_url,
    STATE(97), 1,
      sym_bare_string,
    ACTIONS(111), 2,
      sym_quoted_string,
      sym_filename,
  [529] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(94), 1,
      sym_agent_meta,
    ACTIONS(107), 4,
      anon_sym_domain,
      anon_sym_license,
      anon_sym_terms,
      anon_sym_privacy,
  [542] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym_identifier,
    ACTIONS(117), 1,
      anon_sym_LBRACK,
    ACTIONS(119), 1,
      anon_sym_Enum,
    STATE(44), 1,
      sym_type_value,
    STATE(45), 1,
      sym_type_ref,
  [561] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym_identifier,
    ACTIONS(121), 1,
      sym__indent,
    STATE(78), 1,
      sym_type_ref,
    STATE(85), 1,
      sym_type_reference,
    STATE(125), 1,
      sym_type_list,
  [580] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 5,
      sym__newline,
      sym__dedent,
      anon_sym_LPAREN,
      anon_sym_QMARK,
      sym_quoted_string,
  [591] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym_identifier,
    ACTIONS(125), 1,
      sym__indent,
    STATE(78), 1,
      sym_type_ref,
    STATE(85), 1,
      sym_type_reference,
    STATE(131), 1,
      sym_type_list,
  [610] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym_identifier,
    STATE(51), 1,
      sym_type_ref,
    STATE(79), 1,
      sym_type_reference,
    STATE(92), 1,
      sym_cap_item,
  [626] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_identifier,
    STATE(129), 1,
      sym_bare_string,
    ACTIONS(131), 2,
      sym_quoted_string,
      sym_filename,
  [640] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_DOT,
    ACTIONS(97), 3,
      sym__newline,
      anon_sym_LPAREN,
      anon_sym_COMMA,
  [652] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym_identifier,
    STATE(51), 1,
      sym_type_ref,
    STATE(74), 1,
      sym_type_reference,
    STATE(76), 1,
      sym_typed_item,
  [668] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      sym_identifier,
    STATE(41), 1,
      aux_sym_agent_name_repeat1,
    ACTIONS(138), 2,
      sym__newline,
      sym__indent,
  [682] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym_identifier,
    STATE(51), 1,
      sym_type_ref,
    STATE(79), 1,
      sym_type_reference,
    STATE(80), 1,
      sym_cap_item,
  [698] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      sym_identifier,
    STATE(114), 1,
      sym_bare_string,
    ACTIONS(142), 2,
      sym_quoted_string,
      sym_filename,
  [712] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_QMARK,
    ACTIONS(146), 1,
      sym_quoted_string,
    ACTIONS(148), 2,
      sym__newline,
      sym__dedent,
  [726] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 4,
      sym__newline,
      sym__dedent,
      anon_sym_QMARK,
      sym_quoted_string,
  [736] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym_identifier,
    STATE(51), 1,
      sym_type_ref,
    STATE(74), 1,
      sym_type_reference,
    STATE(83), 1,
      sym_typed_item,
  [752] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 4,
      sym__newline,
      sym__dedent,
      anon_sym_QMARK,
      sym_quoted_string,
  [762] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 4,
      sym__newline,
      sym__dedent,
      anon_sym_QMARK,
      sym_quoted_string,
  [772] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 4,
      sym__newline,
      sym__dedent,
      anon_sym_QMARK,
      sym_quoted_string,
  [782] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      sym_identifier,
    STATE(53), 1,
      aux_sym_agent_name_repeat1,
    ACTIONS(160), 2,
      sym__newline,
      sym__indent,
  [796] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_LPAREN,
    ACTIONS(164), 3,
      sym__newline,
      sym__dedent,
      sym_quoted_string,
  [808] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym_identifier,
    STATE(51), 1,
      sym_type_ref,
    STATE(74), 1,
      sym_type_reference,
    STATE(90), 1,
      sym_typed_item,
  [824] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      sym_identifier,
    STATE(41), 1,
      aux_sym_agent_name_repeat1,
    ACTIONS(168), 2,
      sym__newline,
      sym__indent,
  [838] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 3,
      sym__newline,
      sym__dedent,
      sym_quoted_string,
  [847] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      sym__newline,
    ACTIONS(174), 1,
      sym__dedent,
    STATE(67), 1,
      aux_sym_description_block_repeat1,
  [860] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym_identifier,
    STATE(51), 1,
      sym_type_ref,
    STATE(105), 1,
      sym_type_reference,
  [873] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      sym__newline,
    ACTIONS(178), 1,
      sym__dedent,
    STATE(69), 1,
      aux_sym_requires_block_repeat1,
  [886] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 3,
      sym__newline,
      anon_sym_LPAREN,
      anon_sym_COMMA,
  [895] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    ACTIONS(183), 1,
      sym__newline,
    STATE(59), 1,
      aux_sym_type_list_repeat1,
  [908] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym__newline,
    ACTIONS(187), 1,
      sym__dedent,
    STATE(70), 1,
      aux_sym_input_block_repeat1,
  [921] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym__newline,
    ACTIONS(191), 1,
      sym__dedent,
    STATE(71), 1,
      aux_sym_capabilities_block_repeat1,
  [934] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym__newline,
    ACTIONS(193), 1,
      sym__dedent,
    STATE(70), 1,
      aux_sym_input_block_repeat1,
  [947] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym__newline,
    ACTIONS(197), 1,
      sym__dedent,
    STATE(75), 1,
      aux_sym_type_decl_repeat1,
  [960] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      sym__newline,
    ACTIONS(199), 1,
      sym__dedent,
    STATE(55), 1,
      aux_sym_description_block_repeat1,
  [973] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym__newline,
    ACTIONS(203), 1,
      sym__dedent,
    STATE(77), 1,
      aux_sym_agent_decl_repeat1,
  [986] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      sym_identifier,
    STATE(51), 1,
      sym_type_ref,
    STATE(68), 1,
      sym_type_reference,
  [999] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym__newline,
    ACTIONS(208), 1,
      sym__dedent,
    STATE(67), 1,
      aux_sym_description_block_repeat1,
  [1012] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      sym__newline,
    ACTIONS(210), 1,
      sym__dedent,
    STATE(57), 1,
      aux_sym_requires_block_repeat1,
  [1025] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      sym__newline,
    ACTIONS(215), 1,
      sym__dedent,
    STATE(69), 1,
      aux_sym_requires_block_repeat1,
  [1038] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      sym__newline,
    ACTIONS(220), 1,
      sym__dedent,
    STATE(70), 1,
      aux_sym_input_block_repeat1,
  [1051] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      sym__newline,
    ACTIONS(225), 1,
      sym__dedent,
    STATE(71), 1,
      aux_sym_capabilities_block_repeat1,
  [1064] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_LPAREN,
    ACTIONS(229), 2,
      sym__newline,
      sym__dedent,
  [1075] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(233), 1,
      sym__newline,
    STATE(59), 1,
      aux_sym_type_list_repeat1,
  [1088] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym_quoted_string,
    ACTIONS(237), 2,
      sym__newline,
      sym__dedent,
  [1099] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym__newline,
    ACTIONS(239), 1,
      sym__dedent,
    STATE(81), 1,
      aux_sym_type_decl_repeat1,
  [1112] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym__newline,
    ACTIONS(241), 1,
      sym__dedent,
    STATE(60), 1,
      aux_sym_input_block_repeat1,
  [1125] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym__newline,
    ACTIONS(246), 1,
      sym__dedent,
    STATE(77), 1,
      aux_sym_agent_decl_repeat1,
  [1138] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_LPAREN,
    ACTIONS(164), 2,
      sym__newline,
      anon_sym_COMMA,
  [1149] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      sym_quoted_string,
    ACTIONS(252), 2,
      sym__newline,
      sym__dedent,
  [1160] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym__newline,
    ACTIONS(254), 1,
      sym__dedent,
    STATE(61), 1,
      aux_sym_capabilities_block_repeat1,
  [1173] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym__newline,
    ACTIONS(259), 1,
      sym__dedent,
    STATE(81), 1,
      aux_sym_type_decl_repeat1,
  [1186] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      sym_quoted_string,
    ACTIONS(263), 2,
      sym__newline,
      sym__dedent,
  [1197] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym__newline,
    ACTIONS(265), 1,
      sym__dedent,
    STATE(62), 1,
      aux_sym_input_block_repeat1,
  [1210] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_RPAREN,
    ACTIONS(269), 1,
      anon_sym_COMMA,
    STATE(86), 1,
      aux_sym_type_value_repeat1,
  [1223] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(271), 1,
      sym__newline,
    STATE(73), 1,
      aux_sym_type_list_repeat1,
  [1236] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_COMMA,
    ACTIONS(273), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      aux_sym_type_value_repeat1,
  [1249] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_RPAREN,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    STATE(87), 1,
      aux_sym_type_value_repeat1,
  [1262] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym__newline,
    ACTIONS(280), 1,
      sym__dedent,
    STATE(65), 1,
      aux_sym_agent_decl_repeat1,
  [1275] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym_identifier,
    STATE(78), 1,
      sym_type_ref,
    STATE(91), 1,
      sym_type_reference,
  [1288] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 2,
      sym__newline,
      sym__dedent,
  [1296] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 2,
      sym__newline,
      anon_sym_COMMA,
  [1304] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 2,
      sym__newline,
      sym__dedent,
  [1312] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 2,
      sym__newline,
      sym__dedent,
  [1320] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 2,
      sym__newline,
      sym__dedent,
  [1328] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 2,
      sym__newline,
      sym__dedent,
  [1336] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 2,
      sym__newline,
      sym__dedent,
  [1344] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 2,
      sym__newline,
      sym__dedent,
  [1352] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      sym_identifier,
    STATE(112), 1,
      sym_type_ref,
  [1362] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 2,
      sym__newline,
      sym__dedent,
  [1370] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 2,
      sym__newline,
      sym__dedent,
  [1378] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 2,
      sym__newline,
      sym__dedent,
  [1386] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 2,
      sym__newline,
      sym__dedent,
  [1394] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 2,
      sym__newline,
      sym__dedent,
  [1402] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 2,
      sym__newline,
      sym__dedent,
  [1410] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 2,
      sym__newline,
      sym__dedent,
  [1418] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      sym__newline,
    ACTIONS(302), 1,
      sym__indent,
  [1428] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1436] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 2,
      sym__newline,
      sym__dedent,
  [1444] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      sym_identifier,
    STATE(106), 1,
      sym_agent_name,
  [1454] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 2,
      sym__newline,
      anon_sym_COMMA,
  [1462] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_RBRACK,
    ACTIONS(308), 1,
      anon_sym_DOT,
  [1472] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      anon_sym_RBRACK,
  [1479] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      sym__indent,
  [1486] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_RPAREN,
  [1493] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      sym_identifier,
  [1500] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 1,
      sym_identifier,
  [1507] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      sym_filename,
  [1514] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      anon_sym_COLON,
  [1521] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      sym__newline,
  [1528] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      anon_sym_RPAREN,
  [1535] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      ts_builtin_sym_end,
  [1542] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      sym_identifier,
  [1549] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 1,
      sym_quoted_string,
  [1556] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      sym_identifier,
  [1563] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      sym__newline,
  [1570] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      anon_sym_LPAREN,
  [1577] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      sym__indent,
  [1584] = 2,
    ACTIONS(340), 1,
      sym_text_content,
    ACTIONS(342), 1,
      sym_comment,
  [1591] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(344), 1,
      sym__newline,
  [1598] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(346), 1,
      sym__newline,
  [1605] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      sym__newline,
  [1612] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(350), 1,
      sym_url,
  [1619] = 2,
    ACTIONS(342), 1,
      sym_comment,
    ACTIONS(352), 1,
      sym_text_content,
  [1626] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_RPAREN,
  [1633] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(354), 1,
      sym__newline,
  [1640] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_RBRACK,
  [1647] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(356), 1,
      sym_identifier,
  [1654] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(358), 1,
      anon_sym_RPAREN,
  [1661] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(360), 1,
      sym_identifier,
  [1668] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(362), 1,
      sym_quoted_string,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 105,
  [SMALL_STATE(6)] = 120,
  [SMALL_STATE(7)] = 135,
  [SMALL_STATE(8)] = 150,
  [SMALL_STATE(9)] = 165,
  [SMALL_STATE(10)] = 180,
  [SMALL_STATE(11)] = 195,
  [SMALL_STATE(12)] = 210,
  [SMALL_STATE(13)] = 225,
  [SMALL_STATE(14)] = 240,
  [SMALL_STATE(15)] = 255,
  [SMALL_STATE(16)] = 270,
  [SMALL_STATE(17)] = 285,
  [SMALL_STATE(18)] = 300,
  [SMALL_STATE(19)] = 315,
  [SMALL_STATE(20)] = 330,
  [SMALL_STATE(21)] = 345,
  [SMALL_STATE(22)] = 360,
  [SMALL_STATE(23)] = 375,
  [SMALL_STATE(24)] = 390,
  [SMALL_STATE(25)] = 405,
  [SMALL_STATE(26)] = 426,
  [SMALL_STATE(27)] = 447,
  [SMALL_STATE(28)] = 461,
  [SMALL_STATE(29)] = 480,
  [SMALL_STATE(30)] = 499,
  [SMALL_STATE(31)] = 512,
  [SMALL_STATE(32)] = 529,
  [SMALL_STATE(33)] = 542,
  [SMALL_STATE(34)] = 561,
  [SMALL_STATE(35)] = 580,
  [SMALL_STATE(36)] = 591,
  [SMALL_STATE(37)] = 610,
  [SMALL_STATE(38)] = 626,
  [SMALL_STATE(39)] = 640,
  [SMALL_STATE(40)] = 652,
  [SMALL_STATE(41)] = 668,
  [SMALL_STATE(42)] = 682,
  [SMALL_STATE(43)] = 698,
  [SMALL_STATE(44)] = 712,
  [SMALL_STATE(45)] = 726,
  [SMALL_STATE(46)] = 736,
  [SMALL_STATE(47)] = 752,
  [SMALL_STATE(48)] = 762,
  [SMALL_STATE(49)] = 772,
  [SMALL_STATE(50)] = 782,
  [SMALL_STATE(51)] = 796,
  [SMALL_STATE(52)] = 808,
  [SMALL_STATE(53)] = 824,
  [SMALL_STATE(54)] = 838,
  [SMALL_STATE(55)] = 847,
  [SMALL_STATE(56)] = 860,
  [SMALL_STATE(57)] = 873,
  [SMALL_STATE(58)] = 886,
  [SMALL_STATE(59)] = 895,
  [SMALL_STATE(60)] = 908,
  [SMALL_STATE(61)] = 921,
  [SMALL_STATE(62)] = 934,
  [SMALL_STATE(63)] = 947,
  [SMALL_STATE(64)] = 960,
  [SMALL_STATE(65)] = 973,
  [SMALL_STATE(66)] = 986,
  [SMALL_STATE(67)] = 999,
  [SMALL_STATE(68)] = 1012,
  [SMALL_STATE(69)] = 1025,
  [SMALL_STATE(70)] = 1038,
  [SMALL_STATE(71)] = 1051,
  [SMALL_STATE(72)] = 1064,
  [SMALL_STATE(73)] = 1075,
  [SMALL_STATE(74)] = 1088,
  [SMALL_STATE(75)] = 1099,
  [SMALL_STATE(76)] = 1112,
  [SMALL_STATE(77)] = 1125,
  [SMALL_STATE(78)] = 1138,
  [SMALL_STATE(79)] = 1149,
  [SMALL_STATE(80)] = 1160,
  [SMALL_STATE(81)] = 1173,
  [SMALL_STATE(82)] = 1186,
  [SMALL_STATE(83)] = 1197,
  [SMALL_STATE(84)] = 1210,
  [SMALL_STATE(85)] = 1223,
  [SMALL_STATE(86)] = 1236,
  [SMALL_STATE(87)] = 1249,
  [SMALL_STATE(88)] = 1262,
  [SMALL_STATE(89)] = 1275,
  [SMALL_STATE(90)] = 1288,
  [SMALL_STATE(91)] = 1296,
  [SMALL_STATE(92)] = 1304,
  [SMALL_STATE(93)] = 1312,
  [SMALL_STATE(94)] = 1320,
  [SMALL_STATE(95)] = 1328,
  [SMALL_STATE(96)] = 1336,
  [SMALL_STATE(97)] = 1344,
  [SMALL_STATE(98)] = 1352,
  [SMALL_STATE(99)] = 1362,
  [SMALL_STATE(100)] = 1370,
  [SMALL_STATE(101)] = 1378,
  [SMALL_STATE(102)] = 1386,
  [SMALL_STATE(103)] = 1394,
  [SMALL_STATE(104)] = 1402,
  [SMALL_STATE(105)] = 1410,
  [SMALL_STATE(106)] = 1418,
  [SMALL_STATE(107)] = 1428,
  [SMALL_STATE(108)] = 1436,
  [SMALL_STATE(109)] = 1444,
  [SMALL_STATE(110)] = 1454,
  [SMALL_STATE(111)] = 1462,
  [SMALL_STATE(112)] = 1472,
  [SMALL_STATE(113)] = 1479,
  [SMALL_STATE(114)] = 1486,
  [SMALL_STATE(115)] = 1493,
  [SMALL_STATE(116)] = 1500,
  [SMALL_STATE(117)] = 1507,
  [SMALL_STATE(118)] = 1514,
  [SMALL_STATE(119)] = 1521,
  [SMALL_STATE(120)] = 1528,
  [SMALL_STATE(121)] = 1535,
  [SMALL_STATE(122)] = 1542,
  [SMALL_STATE(123)] = 1549,
  [SMALL_STATE(124)] = 1556,
  [SMALL_STATE(125)] = 1563,
  [SMALL_STATE(126)] = 1570,
  [SMALL_STATE(127)] = 1577,
  [SMALL_STATE(128)] = 1584,
  [SMALL_STATE(129)] = 1591,
  [SMALL_STATE(130)] = 1598,
  [SMALL_STATE(131)] = 1605,
  [SMALL_STATE(132)] = 1612,
  [SMALL_STATE(133)] = 1619,
  [SMALL_STATE(134)] = 1626,
  [SMALL_STATE(135)] = 1633,
  [SMALL_STATE(136)] = 1640,
  [SMALL_STATE(137)] = 1647,
  [SMALL_STATE(138)] = 1654,
  [SMALL_STATE(139)] = 1661,
  [SMALL_STATE(140)] = 1668,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_manifest, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(127),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_manifest_repeat1, 2, 0, 0), SHIFT_REPEAT(122),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_decl, 6, 0, 1),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requires_block, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_block, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_decl, 3, 0, 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_block, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_behavior_block, 3, 0, 2),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description_block, 4, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capabilities_block, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requires_block, 4, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_block, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capabilities_block, 4, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_block, 4, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 5, 0, 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_decl, 5, 0, 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description_block, 5, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requires_block, 5, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_block, 5, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_capabilities_block, 5, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_block, 5, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 6, 0, 1),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(132),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_ref, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_ref, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_agent_name_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_agent_name_repeat1, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(134),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_decl, 3, 0, 6),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_value, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_value, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_value, 4, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_value, 5, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_name, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_reference, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_name, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_reference, 4, 0, 4),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_list_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_list_repeat1, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_description_block_repeat1, 2, 0, 0), SHIFT_REPEAT(133),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_description_block_repeat1, 2, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_requires_block_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_requires_block_repeat1, 2, 0, 0),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_input_block_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_input_block_repeat1, 2, 0, 0),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_capabilities_block_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_capabilities_block_repeat1, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_concept_prop, 2, 0, 5),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_list, 2, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typed_item, 1, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [243] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_agent_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_agent_decl_repeat1, 2, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cap_item, 1, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [256] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_decl_repeat1, 2, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_decl, 4, 0, 7),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_list, 1, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_value_repeat1, 2, 0, 0),
  [277] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_value_repeat1, 2, 0, 0), SHIFT_REPEAT(124),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema_prop, 2, 0, 2),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typed_item, 2, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_property, 1, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent_meta, 2, 0, 3),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_decl, 4, 0, 8),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_concept_prop, 5, 0, 9),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cap_item, 2, 0, 0),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_decl, 5, 0, 10),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bare_string, 1, 0, 0),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [326] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [340] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [342] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [352] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token__dedent] = true,
  },
  [3] = {
    [ts_external_token__indent] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_agent_external_scanner_create(void);
void tree_sitter_agent_external_scanner_destroy(void *);
bool tree_sitter_agent_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_agent_external_scanner_serialize(void *, char *);
void tree_sitter_agent_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_agent(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_agent_external_scanner_create,
      tree_sitter_agent_external_scanner_destroy,
      tree_sitter_agent_external_scanner_scan,
      tree_sitter_agent_external_scanner_serialize,
      tree_sitter_agent_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "agent",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
